version: '3.9'

services:
  cqpweb:
    build: cqpweb
    links: ['db']
    ports:
      - "9090:80"
    volumes:
      - .:/code 
    depends_on:
      - db
    restart: unless-stopped
  db:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=letmein
    volumes:
      - ./mysql/init:/docker-entrypoint-initdb.d
      - ./mysql/data:/var/lib/mysql
    restart: unless-stopped  
