version: '3.9'

services:
  cqpweb:
    build: cqpweb
    links: ['db']
    ports:
      - "80:80"
    volumes:
      - .:/code 
    depends_on:
      - db
  db:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=letmein
    volumes:
      - ./mysql/init:/docker-entrypoint-initdb.d

  
